# -*- coding: utf-8 -*-
"""lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVWI5_f3OIkh_qbKZzWDx1aOKG1F7K_G
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose

# ==============================
# 🔥 BÀI 1: SUPERMARKET
# ==============================

df1 = pd.read_csv('ITA105_Lab_5_Supermarket.csv')

# Datetime
df1['date'] = pd.to_datetime(df1['date'])
df1.set_index('date', inplace=True)

# Missing values
df1['revenue'] = df1['revenue'].fillna(method='ffill')

# Feature engineering
df1['year'] = df1.index.year
df1['month'] = df1.index.month
df1['quarter'] = df1.index.quarter
df1['dayofweek'] = df1.index.dayofweek
df1['is_weekend'] = df1['dayofweek'].apply(lambda x: 1 if x >= 5 else 0)

# Resample
monthly = df1['revenue'].resample('M').sum()
weekly = df1['revenue'].resample('W').sum()

monthly.plot(title='[Bài 1] Doanh thu theo tháng')
plt.show()

weekly.plot(title='[Bài 1] Doanh thu theo tuần')
plt.show()

# Trend
df1['rolling_mean'] = df1['revenue'].rolling(30).mean()
df1[['revenue', 'rolling_mean']].plot(title='[Bài 1] Trend')
plt.show()

# Decomposition
seasonal_decompose(df1['revenue'], model='additive', period=30).plot()
plt.show()


# ==============================
# 🔥 BÀI 2: WEB TRAFFIC
# ==============================

df2 = pd.read_csv('ITA105_Lab_5_Web_traffic.csv')

df2['datetime'] = pd.to_datetime(df2['datetime'])
df2.set_index('datetime', inplace=True)

# Resample hourly
df2 = df2.resample('H').mean()

# Interpolation
df2['visits'] = df2['visits'].interpolate(method='linear')

# Feature
df2['hour'] = df2.index.hour
df2['dayofweek'] = df2.index.dayofweek

# Hourly pattern
df2.groupby('hour')['visits'].mean().plot(title='[Bài 2] Lưu lượng theo giờ')
plt.show()

# Seasonality
df2['visits'].resample('D').mean().plot(title='[Bài 2] Theo ngày')
plt.show()

df2['visits'].resample('W').mean().plot(title='[Bài 2] Theo tuần')
plt.show()


# ==============================
# 🔥 BÀI 3: STOCK
# ==============================

df3 = pd.read_csv('ITA105_Lab_5_Stock.csv')

df3['date'] = pd.to_datetime(df3['date'])
df3.set_index('date', inplace=True)

# Missing values
df3['close_price'] = df3['close_price'].fillna(method='ffill')

# Line plot
df3['close_price'].plot(title='[Bài 3] Giá cổ phiếu')
plt.show()

# Rolling mean
df3['MA7'] = df3['close_price'].rolling(7).mean()
df3['MA30'] = df3['close_price'].rolling(30).mean()

df3[['close_price', 'MA7', 'MA30']].plot(title='[Bài 3] Trend')
plt.show()

# Seasonality theo tháng
df3.groupby(df3.index.month)['close_price'].mean().plot(title='[Bài 3] Seasonality tháng')
plt.show()


# ==============================
# 🔥 BÀI 4: PRODUCTION
# ==============================

df4 = pd.read_csv('ITA105_Lab_5_Production.csv')

df4['week_start'] = pd.to_datetime(df4['week_start'])
df4.set_index('week_start', inplace=True)

# Missing values
df4['production'] = df4['production'].interpolate()

# Feature
df4['week'] = df4.index.isocalendar().week
df4['quarter'] = df4.index.quarter
df4['year'] = df4.index.year

# Trend
df4['rolling_mean'] = df4['production'].rolling(12).mean()

df4[['production', 'rolling_mean']].plot(title='[Bài 4] Trend sản xuất')
plt.show()

# Seasonality theo quý
df4.groupby('quarter')['production'].mean().plot(title='[Bài 4] Seasonality quý')
plt.show()

# Decomposition
seasonal_decompose(df4['production'], model='additive', period=12).plot()
plt.show()